### ISSUE TITLE
Revamp UI

### ISSUE THREAD

**Issue by Kaiiiii** [CS2103AUG2016-W11-C1/main#112]
- [x] Show reminders somehow in tasks
- [x] Make task information more presentable 
- [x]  Make results field scrollable 
- [x] Make copy paste in result
- [x] Make maximised screen
- [x] Word wrap in result panel
- [x]  Show overdue task in red
- [x]  Add a temporary box that says "task added" or something 
- [x] Make result pane horizontal?
- [x] make alert box look nice
- [x] Wrap text for list cell
- [x] Empty list color should be the same

**Comment by cadmusthefounder** [comment]
5. Show overdue task in red
6. Add a temporary box that says "task added" or something

**Comment by cadmusthefounder** [comment]
3) Make result pane horizontal?

**Comment by cadmusthefounder** [comment]
4) Make version number show on title

**Comment by cadmusthefounder** [comment]
5) add syntax highlighting

**Comment by cadmusthefounder** [comment]
6) figure out alert thing. Also if we are going to use alerts in the final product, at least make the box nicer haha

**Comment by yihangho** [comment]
> at least make the box nicer haha

CSS the 💩 out of it
